services:
  app:
    container_name: lilith-realtime
    ports:
      - "8101:80" # Exponer el puerto 8101
    build:
      context: .
    networks:
      network:
    environment:
      - Redis:ConnectionString=localhost:6379

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379" # Exponer el puerto 6379
    volumes:
      - redis_data:/data # Persistir los datos de Redis
    command: ["redis-server", "--appendonly", "yes"] # Habilitar persistencia (AOF)
    networks:
      network:

volumes:
  redis_data:
  
networks:
  network:
    driver: bridge