services:
  app:
    container_name: lilith-realtime
    ports:
      - "8081:80" # Mapea el puerto 8080 del host al puerto 80 del contenedor
      - "8082:443" # Puerto HTTPS
    build:
      context: .
    networks:
      network:
    environment:
      - REDIS__CONNECTIONSTRING=redis:6379
      - CORS__ALLOWEDORIGINS=http://localhost:8100,https://yourfrontenddomain.com
      - ASPNETCORE_URLS=http://+:80;https://+:443

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379" # Exponer el puerto 6379
    volumes:
      - redis_data:/data # Persistir los datos de Redis
    command: ["redis-server", "--appendonly", "yes"] # Habilitar persistencia (AOF)
    networks:
      network:

volumes:
  redis_data:
  
networks:
  network:
    driver: bridge